name: wildcardadventures
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23096
title: 'fasten your seatbelts!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#7b3b0a'
    - '#d5d4b5'
    - '#bd7c1e'
    - '#fdfefc'
  brandStrength: 0.9375
  lightness: 0.9322252557612956
  saturation: 0.9524081712588668
  rhythmicContrast: 0.5
purpose: []
