name: wildcardadventures
favicon: null
layout_spectrum: 0.1440778539981693
typography_spectrum: 0.809103497536853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06377700041048229
  lightness: 0.9322252557612956
  saturation: 0.9524081712588668
  rhythmicContrast: 0.16975750820711255
purpose: []
